### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#1]
The game 'map' area dissapears from view when any section of the canvas is clicked. (While using Firefox Aurora 19.0a2)
![dominion1](https://f.cloud.github.com/assets/2076039/60553/76dcfdc4-5c13-11e2-916f-dfc2462366de.png)

**Comment by codeThatThinks** [comment]
It seems that Firefox uses e.layerX and e.layerY instead of e.offsetX and e.offsetY to get mouse coordinates.

When panning, since e.offsetX doesn't exist, mouse coords are set as null and when the grid is redrawn, the new grid origin cannot be determined and the grid is no longer on screen.

**Comment by codeThatThinks** [comment]
It turns out that e.layerX/Y no longer exists in newer versions of Firefox. Resorted to e.pageX/Y and calculating relative mouse location.

Fixed in d2f3bb6ad3c53d01bc602d3008da0e6de0271003.
