### ISSUE TITLE
Scrollwheel does not work in Firefox

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#11]
Scrolling to zoom does not work with Firefox (Aurora 20.0a2) instead page scrolls.

Can confirm that this function works when using Google Chrome, tested with trackpad and external mouse.

**Comment by luntdotp** [comment]
Looks like we need to use DOMMouseScroll for all browsers.

**Comment by luntdotp** [comment]
While it appears to be possible to make scroll detection work with firefox, I have not found a way to stop the actual page scrolling up and down. Did not commit any changes.

**Comment by bglen** [comment]
Using Firefox, the scroll function that is built into the trackpad on an HP laptop does not seem to zoom the canvas.

**Comment by luntdotp** [comment]
This should be fixed now.
