### ISSUE TITLE
Right-clicking and dragging, then lifting off will drag the canvas.

### ISSUE THREAD

**Issue by bglen** [codeThatThinks/dominion#12]
Right-clicking and dragging, then lifting off will drag the canvas after the right-click menu disappears.

**Comment by luntdotp** [comment]
Could (should) make left click only.

**Comment by codeThatThinks** [comment]
http://stackoverflow.com/questions/1206203/how-to-distinguish-between-left-and-right-mouse-click-with-jquery

**Comment by bglen** [comment]
Also, holding down middle-mouse button will drag the canvas in Safari, it will also drag the canvas in Opera after you zoom.
