### ISSUE TITLE
Multiplayer Support

### ISSUE THREAD

**Issue by codeThatThinks** [codeThatThinks/dominion#14]
Real time multiplayer support, user accounts, and persistent world saving. Will use Node.js server with Socket.io.

**Comment by codeThatThinks** [comment]
Node.js server will be available at http://cloud.ianglen.me for the time being.

**Comment by codeThatThinks** [comment]
Dominion-server repo is up! https://github.com/codeThatThinks/Dominion-server

**Comment by luntdotp** [comment]
I have been looking for an insentive to learn Node.js. I will try to learn it.

**Comment by codeThatThinks** [comment]
The documentation for socket.io probably could be better, but it's actually pretty easy to learn.

**Comment by luntdotp** [comment]
Thanks!

**Comment by codeThatThinks** [comment]
Node.js server will be moved to VPS at http://dominion-server.ianglen.me in the near future.

**Comment by luntdotp** [comment]
I guess we are going to use a login system?
