### ISSUE TITLE
Pages taking ages to load (minutes)

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#15]
I guess this could be due to the node.js server, although my knowledge of how this works is limited. 

Addition: It appears the page is loading but not functioning.

**Comment by codeThatThinks** [comment]
This is almost entirely due to high latency to the node.js server (currently hosted at home). There isn't much that can be done, but socket.io.js should probably be hosted locally with the client, rather than on the server itself.

**Comment by luntdotp** [comment]
Okay.

**Comment by luntdotp** [comment]
"Addition: It appears the page is loading but not functioning."
