### ISSUE TITLE
Canvas does not appear to be taking input.

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#16]
Google Chrome and Internet explorer (9) tested. Cannot use the game although all visual (ui) elements appear.

**Comment by luntdotp** [comment]
Also does not take keyboard input.

**Comment by codeThatThinks** [comment]
It's having issues loading socket.io.js, which is causing game.js to act weird.

**Comment by luntdotp** [comment]
Okay.

**Comment by luntdotp** [comment]
Looks like the problem is solved.
