### ISSUE TITLE
Game not loading.

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#17]
Game showing only the grey canvas. Has been in this state since around approx 10-11am GMT (5-6am EST). 

I think this is a server side problem as no code appears to have been changed before it stopped working. 

Other possible causes:
- Browser had cached working scripts for the game and it reloaded after it had broken. (Highly Unlikely)
- Device specific problem. (Unlikely)

Tested Firefox and Google Chrome. 

Screenshot:
![dominion-blank](https://f.cloud.github.com/assets/2076039/188660/053c244e-7e03-11e2-8b34-4f300e223431.png)

**Comment by luntdotp** [comment]
It appears dominion-server.ianglen.me is down.

**Comment by codeThatThinks** [comment]
Can you open Chrome's web inspector and see what not's loading? If socket.io.js isn't found, the game won't load and throws an exception (needs fixed).

The node,js server currently has lots of bugs that end in a crash. I'm currently going through and fixing them. Error handling currently isn't and should be implemented. What likely happened is that the server encountered one of these bugs, crashed, and never restarted. In that case, it would be down and socket.io.js wouldn't be able to load.

**Comment by luntdotp** [comment]
It looks like it's working now. Socket.io.js appears to be running. All good, great work! PS. What branch should I work on?

**Comment by codeThatThinks** [comment]
I've been working on gh-pages so I could test if any changes actually worked. I'll be cleaning up the piles of commits and moving my changes to Pre-Alpha later today.

**Comment by luntdotp** [comment]
Okay.
