### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#18]
Multiplayer seems to work very well when the server is connected.

As browser doesn't connect to server straight away, a login system should be put in place to ensure that the user cannot play while not connected. A login system would also ensure that a user can maintain control over their country.

Can this all be done whithin the canvas area?

**Comment by codeThatThinks** [comment]
It could be, but the UI API currently doesn't support text boxes. It might be a better idea to use JS to hide/show a div with username, password, and login button.

**Comment by codeThatThinks** [comment]
The div probably would be shown on default, user logs in, div disappears, and canvas says 'Connecting to server...' until it establishes a connection.

**Comment by luntdotp** [comment]
Using the game while not connected could cause problems.

**Comment by KieranFitzgerald** [comment]
Yeah I agree Pete,  people will be angry if there session dosent save to the server. You could have the country number save to a cookie?

**Comment by codeThatThinks** [comment]
Persistence is currently not set up on the server. It is designed to reset the territory array on server restart.

**Comment by luntdotp** [comment]
If you save the country id as a cookie then the game can only be played on one device, that is annoying. (The map cannot be transfered from device to device)

**Comment by codeThatThinks** [comment]
I'll implement persistence when user accounts are implemented.

**Comment by luntdotp** [comment]
Okay, I might work on that a bit later.

**Comment by KieranFitzgerald** [comment]
If the user dosn't want to make an account then a cookie could be a option.

**Comment by luntdotp** [comment]
Why?

**Comment by KieranFitzgerald** [comment]
Not everyone likes to create an account/login

**Comment by codeThatThinks** [comment]
We'll implement user accounts only for now. After Alpha release, we can implement a guest account or something.

**Comment by luntdotp** [comment]
I see your point but in the EU you need to declare cookies.

**Comment by luntdotp** [comment]
I agree with Ian.

**Comment by codeThatThinks** [comment]
Cookies would be a horrible way to store country/territory data. They are vulnerable to modification.

**Comment by KieranFitzgerald** [comment]
I mean just an ID which could link up to a country in the database

**Comment by KieranFitzgerald** [comment]
But yeah that could be added at a later date

**Comment by codeThatThinks** [comment]
No databases are used on the Node.js server. All data is stored in relation to each connection. A guest account would be the best option.

**Comment by luntdotp** [comment]
But the database needs to know not to use that ID again.

**Comment by KieranFitzgerald** [comment]
Yeah, a guest account would be the best option.

**Comment by codeThatThinks** [comment]
Almost done with login system. Just trying to work out the many bugs with accessing the database for storing usernames and passwords.

**Comment by codeThatThinks** [comment]
Login works. Just enter what email and password you'd like to use when logging in for the first time.

Still have to implement email validation, tie user accounts to countries, and per-user territory and entities.
