### ISSUE TITLE
Client Disconnect Takes Too Long

### ISSUE THREAD

**Issue by codeThatThinks** [codeThatThinks/dominion#19]
When a client disconnects, it takes too long to update on the server. This is probably because the server has to wait for the connection to time out in order to register a disconnect.

**Comment by luntdotp** [comment]
What can actually be done about this apart from decreasing the timeout? (Unless volantary disconnect)

**Comment by codeThatThinks** [comment]
I might be able to bind to window close event via jQuery. It could be set up the forcibly send a disconnect event on window close.

Timeouts are sent by the socket.io protocol and cannot be changed.
