### ISSUE TITLE
Currently able to claim territory outside of boundaries.

### ISSUE THREAD

**Issue by bglen** [codeThatThinks/dominion#20]

**Comment by codeThatThinks** [comment]
By boundary, do you mean the large grey rectangle? It's only there because I told it to draw one. No boundary checking is done.

**Comment by luntdotp** [comment]
Should boundaires be removed (not implimented), if they were it would increase the competition element of the game. Although it would be easier to stop other players enjoying the game (not good). You could give people enough guards to protect the land they start with.

**Comment by bglen** [comment]
Boundaries against different territories are also a bit screwed up.

**Comment by codeThatThinks** [comment]
That has to do with the order in which territory units are rendered.
