### ISSUE TITLE
Grid Rendering Issue

### ISSUE THREAD

**Issue by bglen** [codeThatThinks/dominion#24]
Grids lines render incorrectly at bottom of canvas relative to camera view

**Comment by luntdotp** [comment]
![this](https://f.cloud.github.com/assets/2076039/201885/0f4080b0-8101-11e2-8faa-0799f8ba0bef.png)

**Comment by codeThatThinks** [comment]
Fixed in commit 4c88134cccdb319988a387e2452368dcb212dc81
