### ISSUE TITLE
Getting stuck when logging in

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#28]
I cannot log in, it gets stuck on "Logging in..."
(This could be a server issue/server down)
![1](https://f.cloud.github.com/assets/2076039/721006/c20d6e76-dfd2-11e2-9336-61da51d09e87.png)

**Comment by codeThatThinks** [comment]
Seems to be some kind of server side issue: '405 Not Allowed'

**Comment by codeThatThinks** [comment]
This happens when the mysql server is unavailable on the server side, which prevents login credentials from being processed. See codeThatThinks/Dominion-server#1

**Comment by codeThatThinks** [comment]
The SaaS that hosted the server has shutdown and I have moved the server to a personal server. b34f505ce4b334c5f0c8443174641bba15fd0b29 merged some changes and updates client to new url. Login due to a down server should be fixed.
