### ISSUE TITLE
Doesn't Load in Chrome on Windows

### ISSUE THREAD

**Issue by codeThatThinks** [codeThatThinks/dominion#3]
Canvas isn't loading in Chrome on Windows. It does, however, load in Chrome on a Mac.

**Comment by luntdotp** [comment]
If the live demo is the same it loads for me on Windows 8 in Chrome 24.

**Comment by codeThatThinks** [comment]
Seems to work on Chrome running on all platforms except Windows XP.

**Comment by codeThatThinks** [comment]
I can no longer reproduce the issue. Must have been solved in some refactoring or in an update for Chrome.
