### ISSUE TITLE
Resources (Money / Value)

### ISSUE THREAD

**Issue by luntdotp** [codeThatThinks/dominion#31]
Is an in game money / value system going to be implemented so that players can construct buildings, perform work, etc?
(Assuming this is the case can entities be given some sort of value?)

Values for other resources could also be implemented if desired, for example country population.

**Comment by codeThatThinks** [comment]
I think things are heading towards resources being the value that is required to build buildings, construct units, etc. For example, building x would require 10 coal + 100 steel to build.

**Comment by luntdotp** [comment]
That's useful to know, do you have a rough list of resources that you would like to implement? Perhaps Coal, Steel, Food, Workers, Oil, Energy (for example.) 

This would be useful in the wiki.

**Comment by codeThatThinks** [comment]
Added wiki page for gathering resources: https://github.com/codeThatThinks/Dominion/wiki/Gathering-Resources
Added section for a list of resources under Contents on the Home page.
Added section for a list of topographical features under Contents on the Home page.

**Comment by luntdotp** [comment]
Will the resources be kept in a separate table on the database?
