### ISSUE TITLE
More/Better Entity Models

### ISSUE THREAD

**Issue by codeThatThinks** [codeThatThinks/dominion#8]
More complex entities would be good.

Entity ideas:
- military
  - air force bases
  - outposts
  - vehicles
  - military units
  - defense & gun emplacements
- industry
  - mining/raw material processing
  - weapons manufacturing
  - vehicles

Refer to my Dribbble bucket for the style of the renders: [http://dribbble.com/codeThatThinks/buckets/112235-Isometric](http://dribbble.com/codeThatThinks/buckets/112235-Isometric).

**Comment by bglen** [comment]
I've completed a processing plant model that is awaiting the final touches in photoshop.

**Comment by luntdotp** [comment]
I have created a farm building although I am having little luck rendering it. (Also editing.)
![farm1](https://f.cloud.github.com/assets/2076039/173474/ef9bcbda-7add-11e2-9d3e-750b9ac63234.png)

**Comment by codeThatThinks** [comment]
Looks like you're off to a good start. Are you using the template file available in the wiki?

**Comment by bglen** [comment]
Finished the tank model for now, just needs to be scaled and properly rendered.
![tank](https://f.cloud.github.com/assets/3615642/174349/33bf7bd8-7b09-11e2-9c00-6c211487a785.png)

**Comment by codeThatThinks** [comment]
I will render your guys' models with proper lighting if you can email your .blend files.

**Comment by luntdotp** [comment]
Yes. I will send you the file but I will have to do it later. Thanks.

**Comment by bglen** [comment]
The farm building render isn't scaled properly, it's bigger than the factory.

**Comment by luntdotp** [comment]
I can shrink it at some point.

**Comment by codeThatThinks** [comment]
Add any unit or entity ideas to the wiki and document them to the best of your ability. Then submit an issue for that specific kind of entity/unit.
